# Generated by Django 5.1.3 on 2024-11-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Bio', models.TextField()),
                ('phone_num', models.CharField(max_length=12)),
            ],
        ),
    ]
